// src/components/CountriesMappedToContinents.js

export const countriesMappedToContinents = {
    AR: "South America",
    AU: "Oceania",
    AT: "Europe",
    BS: "North America",
    BE: "Europe",
    BO: "South America",
    BR: "South America",
    CA: "North America",
    CL: "South America",
    CN: "Asia",
    CO: "South America",
    CR: "North America",
    HR: "Europe",
    CU: "North America",
    CZ: "Europe",
    DK: "Europe",
    DO: "North America",
    EC: "South America",
    EG: "Africa",
    SV: "North America",
    FI: "Europe",
    FR: "Europe",
    DE: "Europe",
    GR: "Europe",
    GT: "North America",
    HN: "North America",
    HK: "Asia",
    IN: "Asia",
    IE: "Europe",
    IL: "Asia",
    IT: "Europe",
    JM: "North America",
    JP: "Asia",
    LU: "Europe",
    MX: "North America",
    MA: "Africa",
    NL: "Europe",
    NZ: "Oceania",
    NI: "North America",
    NG: "Africa",
    NO: "Europe",
    PY: "South America",
    PE: "South America",
    PL: "Europe",
    PT: "Europe",
    PR: "North America",
    RU: "Europe",
    SA: "Asia",
    ZA: "Africa",
    ES: "Europe",
    SE: "Europe",
    CH: "Europe",
    TW: "Asia",
    TR: "Asia",
    UK: "Europe",
    US: "North America",
    UY: "South America",
    VE: "South America",
    SD: "Africa",
    AF: "Asia",
    AL: "Europe",
    DZ: "Africa",
    AO: "Africa",
    AG: "North America",
    AW: "North America",
    AZ: "Asia",
    BH: "Asia",
    BD: "Asia",
    BB: "North America",
    BY: "Europe",
    BZ: "North America",
    BM: "North America",
    BT: "Asia",
    BW: "Africa",
    VG: "North America",
    BN: "Asia",
    BG: "Europe",
    BF: "Africa",
    MM: "Asia",
    BI: "Africa",
    CM: "Africa",
    CV: "Africa",
    KY: "North America",
    KM: "Africa",
    CG: "Africa",
    CY: "Asia",
    YE: "Asia",
    DJ: "Africa",
    DM: "North America",
    GQ: "Africa",
    EE: "Europe",
    FJ: "Oceania",
    GA: "Africa",
    GM: "Africa",
    GH: "Africa",
    GD: "North America",
    GN: "Africa",
    GW: "Africa",
    GY: "South America",
    HT: "North America",
    HU: "Europe",
    IS: "Europe",
    ID: "Asia",
    IR: "Asia",
    CI: "Africa",
    JO: "Asia",
    KE: "Africa",
    KW: "Asia",
    KP: "Asia",
    KG: "Asia",
    LA: "Asia",
    LV: "Europe",
    LB: "Asia",
    LR: "Africa",
    LI: "Europe",
    LT: "Europe",
    MG: "Africa",
    MY: "Asia",
    ML: "Africa",
    MT: "Europe",
    MR: "Africa",
    MN: "Asia",
    MC: "Europe",
    MZ: "Africa",
    NP: "Asia",
    NE: "Africa",
    OM: "Asia",
    PK: "Asia",
    PA: "North America",
    PH: "Asia",
    QA: "Asia",
    RO: "Europe",
    KN: "North America",
    LC: "North America",
    VC: "North America",
    WS: "Oceania",
    SN: "Africa",
    SG: "Asia",
    SB: "Oceania",
    SZ: "Africa",
    SY: "Asia",
    TH: "Asia",
    TT: "North America",
    TN: "Africa",
    UA: "Europe",
    AE: "Asia",
    VN: "Asia",
    ZW: "Africa",
    ZM: "Africa",
    LK: "Asia",
  };
  