export const countriesMappedToSubcontinents = {
    AR: "South America",
    AU: "Australia and New Zealand",
    AT: "Western Europe",
    BS: "Caribbean",
    BE: "Western Europe",
    BO: "South America",
    BR: "South America",
    CA: "Northern America",
    CL: "South America",
    CN: "Eastern Asia",
    CO: "South America",
    CR: "Central America",
    HR: "Southern Europe",
    CU: "Caribbean",
    CZ: "Eastern Europe",
    DK: "Northern Europe",
    DO: "Caribbean",
    EC: "South America",
    EG: "Northern Africa",
    SV: "Central America",
    FI: "Northern Europe",
    FR: "Western Europe",
    DE: "Western Europe",
    GR: "Southern Europe",
    GT: "Central America",
    HN: "Central America",
    HK: "Eastern Asia",
    IN: "Southern Asia",
    IE: "Northern Europe",
    IL: "Western Asia",
    IT: "Southern Europe",
    JM: "Caribbean",
    JP: "Eastern Asia",
    LU: "Western Europe",
    MX: "Central America",
    MA: "Northern Africa",
    NL: "Western Europe",
    NZ: "Australia and New Zealand",
    NI: "Central America",
    NG: "Western Africa",
    NO: "Northern Europe",
    PY: "South America",
    PE: "South America",
    PL: "Eastern Europe",
    PT: "Southern Europe",
    PR: "Caribbean",
    RU: "Eastern Europe",
    SA: "Western Asia",
    ZA: "Southern Africa",
    ES: "Southern Europe",
    SE: "Northern Europe",
    CH: "Western Europe",
    TW: "Eastern Asia",
    TR: "Western Asia",
    UK: "Northern Europe",
    US: "Northern America",
    UY: "South America",
    VE: "South America",
    SD: "Northern Africa",
    II: "Other",
    AF: "Southern Asia",
    AL: "Southern Europe",
    DZ: "Northern Africa",
    AO: "Middle Africa",
    AG: "Caribbean",
    AW: "Caribbean",
    AZ: "Western Asia",
    BH: "Western Asia",
    BD: "Southern Asia",
    BB: "Caribbean",
    BY: "Eastern Europe",
    BZ: "Central America",
    BM: "Northern America",
    BT: "Southern Asia",
    BW: "Southern Africa",
    VG: "Caribbean",
    BN: "South-Eastern Asia",
    BG: "Eastern Europe",
    BF: "Western Africa",
    MM: "South-Eastern Asia",
    BI: "Eastern Africa",
    CM: "Middle Africa",
    CV: "Western Africa",
    KY: "Caribbean",
    KM: "Eastern Africa",
    CG: "Middle Africa",
    CY: "Western Asia",
    YE: "Western Asia",
    DJ: "Eastern Africa",
    DM: "Caribbean",
    GQ: "Middle Africa",
    EE: "Northern Europe",
    FJ: "Melanesia",
    GA: "Middle Africa",
    GM: "Western Africa",
    GH: "Western Africa",
    GD: "Caribbean",
    GN: "Western Africa",
    GW: "Western Africa",
    GY: "South America",
    HT: "Caribbean",
    HU: "Eastern Europe",
    IS: "Northern Europe",
    ID: "South-Eastern Asia",
    IR: "Southern Asia",
    CI: "Western Africa",
    JO: "Western Asia",
    KE: "Eastern Africa",
    KW: "Western Asia",
    KP: "Eastern Asia",
    KG: "Central Asia",
    LA: "South-Eastern Asia",
    LV: "Northern Europe",
    LB: "Western Asia",
    LR: "Western Africa",
    LI: "Western Europe",
    LT: "Northern Europe",
    MG: "Eastern Africa",
    MY: "South-Eastern Asia",
    ML: "Western Africa",
    MT: "Southern Europe",
    MR: "Western Africa",
    MN: "Eastern Asia",
    MC: "Western Europe",
    MZ: "Eastern Africa",
    NP: "Southern Asia",
    AN: "Caribbean",
    NE: "Western Africa",
    OM: "Western Asia",
    PK: "Southern Asia",
    PA: "Central America",
    PH: "South-Eastern Asia",
    QA: "Western Asia",
    RO: "Eastern Europe",
    KN: "Caribbean",
    LC: "Caribbean",
    VC: "Caribbean",
    WS: "Polynesia",
    SN: "Western Africa",
    SG: "South-Eastern Asia",
    SB: "Melanesia",
    SZ: "Southern Africa",
    SY: "Western Asia",
    TH: "South-Eastern Asia",
    TT: "Caribbean",
    TN: "Northern Africa",
    UA: "Eastern Europe",
    AE: "Western Asia",
    VN: "South-Eastern Asia",
    YU: "Southern Europe",
    ZW: "Southern Africa",
    ZR: "Middle Africa",
    ET: "Eastern Africa",
    KV: "Southern Europe",
    AX: "Northern Europe",
    AS: "Polynesia",
    AD: "Southern Europe",
    AI: "Caribbean",
    AQ: "Antarctica",
    AM: "Western Asia",
    BJ: "Western Africa",
    BA: "Southern Europe",
    BV: "Antarctica",
    IO: "Eastern Africa",
    KH: "South-Eastern Asia",
    CF: "Middle Africa",
    TD: "Middle Africa",
    CX: "Australia and New Zealand",
    CC: "Australia and New Zealand",
    CD: "Middle Africa",
    CK: "Polynesia",
    ER: "Eastern Africa",
    FK: "South America",
    FO: "Northern Europe",
    GF: "South America",
    PF: "Polynesia",
    TF: "Antarctica",
    GE: "Western Asia",
    GI: "Southern Europe",
    GL: "Northern America",
    GP: "Caribbean",
    GU: "Micronesia",
    GG: "Northern Europe",
    HM: "Antarctica",
    VA: "Southern Europe",
    IQ: "Western Asia",
    IM: "Northern Europe",
    JE: "Northern Europe",
    KZ: "Central Asia",
    KI: "Micronesia",
    KR: "Eastern Asia",
    LS: "Southern Africa",
    LY: "Northern Africa",
    MO: "Eastern Asia",
    MK: "Southern Europe",
    MW: "Eastern Africa",
    MV: "Southern Asia",
    MH: "Micronesia",
    MQ: "Caribbean",
    MU: "Eastern Africa",
    YT: "Eastern Africa",
    FM: "Micronesia",
    MD: "Eastern Europe",
    ME: "Southern Europe",
    MS: "Caribbean",
    NA: "Southern Africa",
    NR: "Micronesia",
    NC: "Melanesia",
    NU: "Polynesia",
    NF: "Australia and New Zealand",
    MP: "Micronesia",
    PW: "Micronesia",
    PS: "Western Asia",
    PG: "Melanesia",
    PN: "Polynesia",
    RE: "Eastern Africa",
    RW: "Eastern Africa",
    BL: "Caribbean",
    SH: "Western Africa",
    MF: "Caribbean",
    PM: "Northern America",
    SM: "Southern Europe",
    ST: "Middle Africa",
    RS: "Southern Europe",
    SC: "Eastern Africa",
    SL: "Western Africa",
    SK: "Eastern Europe",
    SI: "Southern Europe",
    SO: "Eastern Africa",
    GS: "Antarctica",
    SR: "South America",
    SJ: "Northern Europe",
    TJ: "Central Asia",
    TZ: "Eastern Africa",
    TL: "South-Eastern Asia",
    TG: "Western Africa",
    TK: "Polynesia",
    TO: "Polynesia",
    TM: "Central Asia",
    TC: "Caribbean",
    TV: "Polynesia",
    UG: "Eastern Africa",
    UM: "Micronesia",
    UZ: "Central Asia",
    VU: "Melanesia",
    VI: "Caribbean",
    WF: "Polynesia",
    EH: "Northern Africa",
    ZM: "Eastern Africa",
    LK: "Southern Asia",
  };
  